const questions = {
    pt: [
        "Se você pudesse ter qualquer superpoder, qual seria?",
        "Qual foi o pior corte de cabelo que você já teve?",
        "Se você fosse um animal, qual seria e por quê?",
        "Qual é o fato mais inútil que você conhece?",
        "Qual filme você pode assistir várias vezes sem cansar?",
        "Qual habilidade você gostaria de aprender?",
        "O que você faz melhor do que a maioria das pessoas?",
        "Qual é o seu hobby favorito que pouca gente sabe?",
        "Qual é o lugar dos seus sonhos para visitar?",
        "Qual foi a comida mais estranha que você já experimentou?",
        "Você prefere praia, montanha ou cidade?",
        "Qual foi sua melhor memória de viagem?",
        "O que te faz perder a noção do tempo?",
        "Qual pequeno hábito mudou sua vida?",
        "Pelo que você é grato hoje?",
        "O que felicidade significa para você?",
        "Você preferiria explorar o espaço ou o fundo do mar?",
        "Você é mais uma pessoa matutina ou noturna?",
        "Você preferiria viajar para o passado ou para o futuro?",
        "Se você ganhasse na loteria amanhã, qual seria a primeira coisa que faria?",
        "Qual foi o melhor conselho que você já recebeu?",
        "Se você pudesse jantar com qualquer pessoa, viva ou morta, quem seria?",
        "Qual foi a coisa mais espontânea que você já fez?",
        "Qual música você poderia ouvir pelo resto da vida?",
        "Se você pudesse morar em qualquer época da história, qual escolheria?",
        "Qual foi o sonho mais estranho que você já teve?",
        "O que você faria se não precisasse trabalhar para viver?",
        "Qual é o seu maior medo irracional?",
        "Se você pudesse dominar instantaneamente um instrumento, qual seria?",
        "Qual foi a maior aventura da sua vida até agora?",
        "Se você pudesse mudar uma decisão do passado, qual seria?",
        "Qual série você recomendaria para qualquer pessoa?",
        "Se você fosse escrever um livro, sobre o que seria?",
        "Qual foi o presente mais significativo que você já recebeu?",
        "Se você pudesse ter uma conversa com seu eu de 10 anos atrás, o que diria?",
        "Qual é a comida que te lembra infância?",
        "Se sua vida fosse um filme, qual seria o gênero?",
        "Qual foi a maior lição que você aprendeu com um erro?",
        "Qual foi o momento mais engraçado que você já passou?",
        "O que você faria se não tivesse medo de falhar?",
        "Que livro ou filme mudou sua perspectiva sobre a vida?",
        "Como você se imagina daqui a 10 anos?",
        "Qual é a sua lembrança favorita da infância?",
        "Qual parte da sua personalidade você mais protege?",
        "Quando você se sente mais você mesmo?",
        "Qual legado você gostaria de deixar no mundo?",
        "O que você aprendeu sobre relacionamentos observando seus pais?",
        "Se você pudesse viver em qualquer cidade do mundo, qual escolheria?",
        "Qual foi o melhor show ou evento ao vivo que você já foi?"
    ],
    en: [
        "If you could have any superpower, what would it be?",
        "What was the worst haircut you've ever had?",
        "If you were an animal, which one would you be and why?",
        "What's the most useless fact you know?",
        "What movie can you watch over and over without getting tired of it?",
        "What skill would you like to learn?",
        "What do you do better than most people?",
        "What's your favorite hobby that few people know about?",
        "What's your dream place to visit?",
        "What's the strangest food you've ever tried?",
        "Do you prefer the beach, the mountains, or the city?",
        "What's your best travel memory?",
        "What makes you lose track of time?",
        "What small habit changed your life?",
        "What are you grateful for today?",
        "What does happiness mean to you?",
        "Would you rather explore outer space or the deep sea?",
        "Are you more of a morning person or a night owl?",
        "Would you rather travel to the past or to the future?",
        "If you won the lottery tomorrow, what's the first thing you'd do?",
        "What's the best advice you've ever received?",
        "If you could have dinner with anyone, alive or dead, who would it be?",
        "What's the most spontaneous thing you've ever done?",
        "What song could you listen to for the rest of your life?",
        "If you could live in any era of history, which would you choose?",
        "What's the strangest dream you've ever had?",
        "What would you do if you didn't have to work for a living?",
        "What's your biggest irrational fear?",
        "If you could instantly master any instrument, which would it be?",
        "What's the greatest adventure of your life so far?",
        "If you could change one decision from your past, what would it be?",
        "What TV show would you recommend to anyone?",
        "If you were to write a book, what would it be about?",
        "What's the most meaningful gift you've ever received?",
        "If you could talk to your self from 10 years ago, what would you say?",
        "What food reminds you of your childhood?",
        "If your life were a movie, what genre would it be?",
        "What's the biggest lesson you've learned from a mistake?",
        "What's the funniest moment you've ever experienced?",
        "What would you do if you weren't afraid of failing?",
        "What book or movie changed your perspective on life?",
        "Where do you see yourself in 10 years?",
        "What's your favorite childhood memory?",
        "What part of your personality do you protect the most?",
        "When do you feel the most like yourself?",
        "What legacy would you like to leave in the world?",
        "What did you learn about relationships by watching your parents?",
        "If you could live in any city in the world, which would you choose?",
        "What's the best concert or live event you've ever been to?"
    ]
};
