const questions = [
    "Se você pudesse ter qualquer superpoder, qual seria?",
    "Qual foi o pior corte de cabelo que você já teve?",
    "Se você fosse um animal, qual seria e por quê?",
    "Qual é o fato mais inútil que você conhece?",
    "Qual filme você pode assistir várias vezes sem cansar?",
    "Qual habilidade você gostaria de aprender?",
    "O que você faz melhor do que a maioria das pessoas?",
    "Qual é o seu hobby favorito que pouca gente sabe?",
    "Qual é o lugar dos seus sonhos para visitar?",
    "Qual foi a comida mais estranha que você já experimentou?",
    "Você prefere praia, montanha ou cidade?",
    "Qual foi sua melhor memória de viagem?",
    "O que te faz perder a noção do tempo?",
    "Qual pequeno hábito mudou sua vida?",
    "Pelo que você é grato hoje?",
    "O que felicidade significa para você?",
    "Você preferiria explorar o espaço ou o fundo do mar?",
    "Você é mais uma pessoa matutina ou noturna?",
    "Você preferiria viajar para o passado ou para o futuro?",
    "Se você ganhasse na loteria amanhã, qual seria a primeira coisa que faria?",
    "Qual foi o melhor conselho que você já recebeu?",
    "Se você pudesse jantar com qualquer pessoa, viva ou morta, quem seria?",
    "Qual foi a coisa mais espontânea que você já fez?",
    "Qual música você poderia ouvir pelo resto da vida?",
    "Se você pudesse morar em qualquer época da história, qual escolheria?",
    "Qual foi o sonho mais estranho que você já teve?",
    "O que você faria se não precisasse trabalhar para viver?",
    "Qual é o seu maior medo irracional?",
    "Se você pudesse dominar instantaneamente um instrumento, qual seria?",
    "Qual foi a maior aventura da sua vida até agora?",
    "Se você pudesse mudar uma decisão do passado, qual seria?",
    "Qual série você recomendaria para qualquer pessoa?",
    "Se você fosse escrever um livro, sobre o que seria?",
    "Qual foi o presente mais significativo que você já recebeu?",
    "Se você pudesse ter uma conversa com seu eu de 10 anos atrás, o que diria?",
    "Qual é a comida que te lembra infância?",
    "Se sua vida fosse um filme, qual seria o gênero?",
    "Qual foi a maior lição que você aprendeu com um erro?",
    "Se você pudesse acordar amanhã com uma nova habilidade, qual seria?",
    "Qual foi o momento mais engraçado que você já passou?",
    "O que você faria se não tivesse medo de falhar?",
    "Qual foi o momento mais marcante da sua vida até agora?",
    "Que livro ou filme mudou sua perspectiva sobre a vida?",
    "Como você se imagina daqui a 10 anos?",
    "Qual é a sua lembrança favorita da infância?",
    "Qual parte da sua personalidade você mais protege?",
    "Quando você se sente mais você mesmo?",
    "Qual legado você gostaria de deixar no mundo?",
    "O que você aprendeu sobre relacionamentos observando seus pais?"
];
